version: '2'

services:
  aresxbot:
    build: .
    image: aresxbot:latest
    container_name: aresxbot
    restart: unless-stopped
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_NOLOGO=true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - .data:/data/db
